# Generated by Django 5.1.2 on 2024-10-11 09:29

import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=myapp.models.get_file_name)),
                ('descriptions', models.TextField()),
                ('status', models.BooleanField(default=0, help_text='0 - show, 1- hidden')),
                ('trending', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=myapp.models.get_file_name)),
                ('quantity', models.IntegerField()),
                ('selling_price', models.FloatField()),
                ('original_price', models.FloatField()),
                ('descriptions', models.TextField()),
                ('status', models.BooleanField(default=0, help_text='0 - show, 1- hidden')),
                ('trending', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
        ),
    ]
