# Generated by Django 5.1.2 on 2024-10-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
